#include "stdafx.h"

#include "FisheyePass.h"

#include "AfxShaders.h"
#include "WrpConsole.h" // advancedfx::Message (outcome-change diagnostics)

#include "../shaders/build/afx_drawtexture_vs_5_0.h" // autogenerated (reused VS)
#include "../shaders/build/afx_fisheye_ps_5_0.h"     // autogenerated (barrel-distortion PS)

#define _XM_NO_INTRINSICS_
#include <DirectXMath.h>

namespace {

// Reference distortion at strength 1.0 -- tuned for a subtle GoPro/action-cam wide-lens
// look (the GMod Action Cam reference used a faint dudv refract, not an extreme fisheye).
// strength scales both linearly.
constexpr float kBaseK1 = 0.22f;
constexpr float kBaseK2 = 0.10f;

// Same 52-byte vertex layout afx_drawtexture_vs_5_0 expects (POSITION + COLOR + 3x TEXCOORD).
// Only POSITION (NDC) and TEXCOORD0.xy (UV) are filled; the rest is padding the VS ignores.
struct Vertex {
	float x, y, z;
	DWORD diffuse;
	float t0u, t0v, t0w;
	float t1u, t1v, t1w;
	float t2u, t2v, t2w;
};

// Matches the VS_CONSTANT_BUFFER cbuffer in afx_drawtexture_vs_5_0.fxc. Only the matrix is
// used; identity so vertex positions pass straight through as NDC.
struct VS_CONSTANT_BUFFER {
	DirectX::XMFLOAT4X4 matrix;
	DirectX::XMFLOAT4 plane0;
	DirectX::XMFLOAT4 planeN;
	DirectX::XMFLOAT4 screenInfo;
};

// Matches the PS_CONSTANT_BUFFER cbuffer in afx_fisheye_ps_5_0.fxc.
struct PS_CONSTANT_BUFFER {
	float k1, k2, aspect, unused;
};

// Fallback only: map a TYPELESS backbuffer format to a typed format for the SRV (normally the
// RTV's own typed format is used). Same table as ViewportScaler.cpp.
DXGI_FORMAT TypedFromTypeless(DXGI_FORMAT f) {
	switch (f) {
	case DXGI_FORMAT_R8G8B8A8_TYPELESS:    return DXGI_FORMAT_R8G8B8A8_UNORM;
	case DXGI_FORMAT_B8G8R8A8_TYPELESS:    return DXGI_FORMAT_B8G8R8A8_UNORM;
	case DXGI_FORMAT_B8G8R8X8_TYPELESS:    return DXGI_FORMAT_B8G8R8X8_UNORM;
	case DXGI_FORMAT_R10G10B10A2_TYPELESS: return DXGI_FORMAT_R10G10B10A2_UNORM;
	case DXGI_FORMAT_R16G16B16A16_TYPELESS:return DXGI_FORMAT_R16G16B16A16_FLOAT;
	default:                               return f;
	}
}

// Full-NDC quad (triangle strip), top row first so UV.v=0 maps to screen top.
const Vertex c_Quad[4] = {
	{ -1.0f,  1.0f, 0.0f, 0xffffffff, 0.0f, 0.0f, 0.0f, 0,0,0, 0,0,0 }, // top-left     uv(0,0)
	{  1.0f,  1.0f, 0.0f, 0xffffffff, 1.0f, 0.0f, 0.0f, 0,0,0, 0,0,0 }, // top-right    uv(1,0)
	{ -1.0f, -1.0f, 0.0f, 0xffffffff, 0.0f, 1.0f, 0.0f, 0,0,0, 0,0,0 }, // bottom-left  uv(0,1)
	{  1.0f, -1.0f, 0.0f, 0xffffffff, 1.0f, 1.0f, 0.0f, 0,0,0, 0,0,0 }, // bottom-right uv(1,1)
};

} // namespace

CFisheyePass::~CFisheyePass() {
	EndDevice();
}

bool CFisheyePass::Ready() const {
	return m_Device && m_DeviceContext && m_VertexShader && m_PixelShader && m_InputLayout
		&& m_VertexBuffer && m_VsConstantBuffer && m_PsConstantBuffer && m_SamplerState
		&& m_RasterizerState && m_DepthStencilState && m_BlendState;
}

void CFisheyePass::BeginDevice(ID3D11Device* device) {
	EndDevice();

	if (nullptr == device)
		return;

	device->AddRef();
	m_Device = device;
	m_Device->CreateDeferredContext(0, &m_DeviceContext);

	// Vertex shader + input layout (reuse the proven afx_drawtexture VS).
	{
		size_t size;
		void* so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_vs_5_0.acs", ShaderCombo_afx_drawtexture_vs_5_0::GetCombo(), size);
		if (so) {
			m_Device->CreateVertexShader(so, size, NULL, &m_VertexShader);

			D3D11_INPUT_ELEMENT_DESC inputDesc[5] = {
				{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,  0, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"COLOR",    0, DXGI_FORMAT_B8G8R8A8_UNORM,  0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 1, DXGI_FORMAT_R32G32B32_FLOAT, 0, 28, D3D11_INPUT_PER_VERTEX_DATA, 0},
				{"TEXCOORD", 2, DXGI_FORMAT_R32G32B32_FLOAT, 0, 40, D3D11_INPUT_PER_VERTEX_DATA, 0},
			};
			m_Device->CreateInputLayout(inputDesc, 5, so, size, &m_InputLayout);
		}
		if (so) free(so);
	}

	// Pixel shader (barrel distortion).
	{
		size_t size;
		void* so = LoadFromAcsShaderFileInMemory(L"afx_fisheye_ps_5_0.acs", ShaderCombo_afx_fisheye_ps_5_0::GetCombo(), size);
		if (so) {
			m_Device->CreatePixelShader(so, size, NULL, &m_PixelShader);
		}
		if (so) free(so);
	}

	// Static NDC quad vertex buffer.
	{
		D3D11_BUFFER_DESC bd = {};
		bd.ByteWidth = sizeof(c_Quad);
		bd.Usage = D3D11_USAGE_IMMUTABLE;
		bd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
		D3D11_SUBRESOURCE_DATA srd = {};
		srd.pSysMem = c_Quad;
		m_Device->CreateBuffer(&bd, &srd, &m_VertexBuffer);
	}

	// Static identity VS constant buffer (NDC pass-through).
	{
		VS_CONSTANT_BUFFER cb = {};
		cb.matrix = DirectX::XMFLOAT4X4(
			1, 0, 0, 0,
			0, 1, 0, 0,
			0, 0, 1, 0,
			0, 0, 0, 1);

		D3D11_BUFFER_DESC bd = {};
		bd.ByteWidth = sizeof(cb);
		bd.Usage = D3D11_USAGE_IMMUTABLE;
		bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		D3D11_SUBRESOURCE_DATA srd = {};
		srd.pSysMem = &cb;
		m_Device->CreateBuffer(&bd, &srd, &m_VsConstantBuffer);
	}

	// Per-frame PS constant buffer (k1/k2/aspect via UpdateSubresource on the deferred context).
	{
		D3D11_BUFFER_DESC bd = {};
		bd.ByteWidth = sizeof(PS_CONSTANT_BUFFER);
		bd.Usage = D3D11_USAGE_DEFAULT;
		bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		m_Device->CreateBuffer(&bd, nullptr, &m_PsConstantBuffer);
	}

	// Linear clamp sampler.
	{
		D3D11_SAMPLER_DESC sd = {};
		sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		sd.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		sd.ComparisonFunc = D3D11_COMPARISON_ALWAYS;
		sd.MinLOD = 0;
		sd.MaxLOD = D3D11_FLOAT32_MAX;
		m_Device->CreateSamplerState(&sd, &m_SamplerState);
	}

	// Solid fill, no culling.
	{
		D3D11_RASTERIZER_DESC rd = {};
		rd.FillMode = D3D11_FILL_SOLID;
		rd.CullMode = D3D11_CULL_NONE;
		rd.DepthClipEnable = TRUE;
		m_Device->CreateRasterizerState(&rd, &m_RasterizerState);
	}

	// Depth test/write disabled.
	{
		D3D11_DEPTH_STENCIL_DESC dd = {};
		dd.DepthEnable = FALSE;
		dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		dd.DepthFunc = D3D11_COMPARISON_ALWAYS;
		dd.StencilEnable = FALSE;
		m_Device->CreateDepthStencilState(&dd, &m_DepthStencilState);
	}

	// Opaque overwrite (the whole frame is redrawn).
	{
		D3D11_BLEND_DESC bd = {};
		bd.RenderTarget[0].BlendEnable = FALSE;
		bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
		m_Device->CreateBlendState(&bd, &m_BlendState);
	}
}

void CFisheyePass::ReleaseTemp() {
	if (m_TempSrv) { m_TempSrv->Release(); m_TempSrv = nullptr; }
	if (m_TempTexture) { m_TempTexture->Release(); m_TempTexture = nullptr; }
	m_TempWidth = 0;
	m_TempHeight = 0;
	m_TempFormat = DXGI_FORMAT_UNKNOWN;
}

void CFisheyePass::EndDevice() {
	ReleaseTemp();

	if (m_BlendState) { m_BlendState->Release(); m_BlendState = nullptr; }
	if (m_DepthStencilState) { m_DepthStencilState->Release(); m_DepthStencilState = nullptr; }
	if (m_RasterizerState) { m_RasterizerState->Release(); m_RasterizerState = nullptr; }
	if (m_SamplerState) { m_SamplerState->Release(); m_SamplerState = nullptr; }
	if (m_PsConstantBuffer) { m_PsConstantBuffer->Release(); m_PsConstantBuffer = nullptr; }
	if (m_VsConstantBuffer) { m_VsConstantBuffer->Release(); m_VsConstantBuffer = nullptr; }
	if (m_VertexBuffer) { m_VertexBuffer->Release(); m_VertexBuffer = nullptr; }
	if (m_InputLayout) { m_InputLayout->Release(); m_InputLayout = nullptr; }
	if (m_PixelShader) { m_PixelShader->Release(); m_PixelShader = nullptr; }
	if (m_VertexShader) { m_VertexShader->Release(); m_VertexShader = nullptr; }
	if (m_DeviceContext) { m_DeviceContext->Release(); m_DeviceContext = nullptr; }
	if (m_Device) { m_Device->Release(); m_Device = nullptr; }
}

bool CFisheyePass::EnsureTemp(const D3D11_TEXTURE2D_DESC& bb, DXGI_FORMAT viewFormat) {
	if (m_TempTexture && m_TempSrv
		&& m_TempWidth == bb.Width && m_TempHeight == bb.Height && m_TempFormat == viewFormat)
		return true;

	ReleaseTemp();

	D3D11_TEXTURE2D_DESC td = {};
	td.Width = bb.Width;
	td.Height = bb.Height;
	td.MipLevels = 1;
	td.ArraySize = 1;
	td.Format = viewFormat;
	td.SampleDesc.Count = 1; // single-sample so it can back an SRV
	td.SampleDesc.Quality = 0;
	td.Usage = D3D11_USAGE_DEFAULT;
	td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	if (FAILED(m_Device->CreateTexture2D(&td, nullptr, &m_TempTexture)) || !m_TempTexture) {
		ReleaseTemp();
		return false;
	}

	D3D11_SHADER_RESOURCE_VIEW_DESC sd = {};
	sd.Format = viewFormat;
	sd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	sd.Texture2D.MostDetailedMip = 0;
	sd.Texture2D.MipLevels = 1;
	if (FAILED(m_Device->CreateShaderResourceView(m_TempTexture, &sd, &m_TempSrv)) || !m_TempSrv) {
		ReleaseTemp();
		return false;
	}

	m_TempWidth = bb.Width;
	m_TempHeight = bb.Height;
	m_TempFormat = viewFormat;
	return true;
}

void CFisheyePass::Apply(ID3D11DeviceContext* pImmediateContext, ID3D11RenderTargetView* pTarget,
	float strength) {
	// Diagnostics: only emit when the OUTCOME changes (no per-frame spam) -- same pattern as
	// CViewportScaler::Blit.
	static int s_prevCode = -999;
	auto changed = [&](int code) { if (s_prevCode != code) { s_prevCode = code; return true; } return false; };

	if (!Ready() || !pImmediateContext || !pTarget) {
		if (changed(1)) advancedfx::Message("[fisheye] SKIP: ready=%d ctx=%p tgt=%p\n",
			(int)Ready(), (void*)pImmediateContext, (void*)pTarget);
		return;
	}
	if (!(strength > 0.0f))
		return;

	ID3D11Resource* pResource = nullptr;
	pTarget->GetResource(&pResource);
	if (!pResource)
		return;

	ID3D11Texture2D* pBackbuffer = nullptr;
	if (FAILED(pResource->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&pBackbuffer)) || !pBackbuffer) {
		if (changed(2)) advancedfx::Message("[fisheye] SKIP: RTV resource is not a Texture2D\n");
		pResource->Release();
		return;
	}

	D3D11_TEXTURE2D_DESC bbDesc;
	pBackbuffer->GetDesc(&bbDesc);

	D3D11_RENDER_TARGET_VIEW_DESC rtvDesc;
	pTarget->GetDesc(&rtvDesc);
	DXGI_FORMAT viewFmt = rtvDesc.Format;
	if (viewFmt == DXGI_FORMAT_UNKNOWN) viewFmt = TypedFromTypeless(bbDesc.Format);

	if (!EnsureTemp(bbDesc, viewFmt)) {
		if (changed(3)) advancedfx::Message("[fisheye] SKIP: EnsureTemp failed (%ux%u bbfmt=%d viewfmt=%d)\n",
			bbDesc.Width, bbDesc.Height, (int)bbDesc.Format, (int)viewFmt);
		pBackbuffer->Release();
		pResource->Release();
		return;
	}

	if (changed(5)) advancedfx::Message("[fisheye] RUN: bb=%ux%u strength=%.2f\n",
		bbDesc.Width, bbDesc.Height, strength);

	// 1. Snapshot the rendered frame (resolve if the backbuffer is MSAA).
	if (bbDesc.SampleDesc.Count > 1)
		m_DeviceContext->ResolveSubresource(m_TempTexture, 0, pBackbuffer, 0, viewFmt);
	else
		m_DeviceContext->CopyResource(m_TempTexture, pBackbuffer);

	// 2. Update the distortion constants for this frame.
	{
		PS_CONSTANT_BUFFER cb = {};
		cb.k1 = kBaseK1 * strength;
		cb.k2 = kBaseK2 * strength;
		cb.aspect = bbDesc.Height > 0 ? (float)bbDesc.Width / (float)bbDesc.Height : 1.0f;
		cb.unused = 0.0f;
		m_DeviceContext->UpdateSubresource(m_PsConstantBuffer, 0, nullptr, &cb, 0, 0);
	}

	// 3. Redraw the whole frame through the distortion shader (full-backbuffer viewport).
	ID3D11RenderTargetView* rtvs[1] = { pTarget };
	m_DeviceContext->OMSetRenderTargets(1, rtvs, nullptr);

	D3D11_VIEWPORT vp = {};
	vp.TopLeftX = 0.0f;
	vp.TopLeftY = 0.0f;
	vp.Width = (float)bbDesc.Width;
	vp.Height = (float)bbDesc.Height;
	vp.MinDepth = 0.0f;
	vp.MaxDepth = 1.0f;
	m_DeviceContext->RSSetViewports(1, &vp);

	m_DeviceContext->IASetInputLayout(m_InputLayout);
	UINT stride = sizeof(Vertex);
	UINT offset = 0;
	m_DeviceContext->IASetVertexBuffers(0, 1, &m_VertexBuffer, &stride, &offset);
	m_DeviceContext->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);

	m_DeviceContext->VSSetShader(m_VertexShader, nullptr, 0);
	m_DeviceContext->VSSetConstantBuffers(0, 1, &m_VsConstantBuffer);
	m_DeviceContext->PSSetShader(m_PixelShader, nullptr, 0);
	m_DeviceContext->PSSetConstantBuffers(0, 1, &m_PsConstantBuffer);
	m_DeviceContext->PSSetShaderResources(0, 1, &m_TempSrv);
	m_DeviceContext->PSSetSamplers(0, 1, &m_SamplerState);

	m_DeviceContext->RSSetState(m_RasterizerState);
	m_DeviceContext->OMSetDepthStencilState(m_DepthStencilState, 0);
	const float blendFactor[4] = { 0, 0, 0, 0 };
	m_DeviceContext->OMSetBlendState(m_BlendState, blendFactor, 0xffffffff);

	m_DeviceContext->Draw(4, 0);

	// Replay on the immediate context, restoring its state so the following UI pass is intact.
	ID3D11CommandList* pCommandList = nullptr;
	m_DeviceContext->FinishCommandList(FALSE, &pCommandList);
	if (pCommandList) {
		pImmediateContext->ExecuteCommandList(pCommandList, TRUE);
		pCommandList->Release();
	}

	pBackbuffer->Release();
	pResource->Release();
}
